### ISSUE TITLE
Make sure your $tu configuration exposes every information.  Error

### ISSUE THREAD

**Issue by kiliss** [Nxve/AutoMudaeExt#3]
how to fix "Couldn't retrieve needed info for user [${user.username}]. Make sure your $tu configuration exposes every information."? any idea?

**Comment by Nxve** [comment]
It expects your _$tu_ command to return needed information from Mudae, which would be: rolls left, current power, $rt availability, character claim availability and power consumption upon claiming kakera.

But you're probably getting this message because it can only run in pt-br mudae for now. It is planned to support other languages in May.
